### ISSUE TITLE
Update PHPCompatibility to 8.1.0 and PHP_CodeSniffer to 3.3.0

### ISSUE THREAD

**Issue by valendesigns** [wptide/wptide#116]
New versions of both `PHPCompatibility` and `PHP_CodeSniffer` have been released and we need to test and update to the latest stable versions inside the PHPCS Server `Dockerfile`.

**Comment by valendesigns** [comment]
Actually, we can only update `PHP_CodeSniffer` at this time. The `framework-rulesets` have not landed in a tag yet for `PHPCompatibility`.

**Comment by jeffpaul** [comment]
Note that per @jrfnl... re: upgrading to WPCS 1.0.0 - also don't forget to change from using `PHPCompatibility` to `PHPCompatibilityWP` (if that hasn't been done already)

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535487429000100) today, we're keeping this in the `1.0.0` release, work has started in https://github.com/wptide/wptide/tree/bugfix/docker-setup, and we cannot update to PHP_CodeSniffer 3.3+ due to failed audits so this needs some research.

**Comment by jrfnl** [comment]
FYI: both PHPCompatibility as well as WPCS are compliant with PHPCS 2.x as well as 3.x, so not being able to update PHP_CodeSniffer yet( for whatever reason), is not a blocker to update the other dependencies.

**Comment by jeffpaul** [comment]
Note that this issue was [referenced in Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1543353095092100).

**Comment by valendesigns** [comment]
Fixed in the 1.0.0-beta2 branch
