### ISSUE TITLE
404 on plugin audit endpoint

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#141]
### Description

From @grappler on [Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1530043649000466):
I seem to have found one that is not working https://wptide.org/api/tide/v1/audit/wporg/plugin/hide-jetpack-promotions/

Getting:
code | "rest_post_invalid_altid_lookup"
message | "Invalid post lookup."
data |  
status | 404

**Comment by valendesigns** [comment]
This means the plugin hasn’t been audited. Some plugins and themes either failed the phpcs audit or were missed due to me taking the services down due to issues the day before WCEU. Until the new endpoint that initiates audits is implemented or the item is updated and picked up by the sync server there will be missing items in the Tide API.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535488207000100) today, @valendesigns to run this audit locally to see if it fails.  If this is a real issue, we'll add to the `1.0.0` release.

**Comment by kkoppenhaver** [comment]
This happens when a plugin hasn't been audited yet.

You can trigger an audit by appending a version number to the URL, for example `https://wptide.org/api/tide/v1/audit/wporg/plugin/hide-jetpack-promotions/1.0.0`.

Now that we've run an audit on this plugin, the original URL in this ticket resolves.

**Comment by jeffpaul** [comment]
Thanks for the triage on this one @kkoppenhaver, much appreciated!  @grappler does that update help clear things up for you?
