### ISSUE TITLE
Prevent API from creating API keys/secrets with the # sign

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#146]
@rheinardkorf commented on [Fri Jul 20 2018](https://github.com/wptide/wporg-tide-api/issues/3)

When using the # symbol in .env files it gets treated as a comment marker. Thus authentication with the API fails.

It is not possible to escape the # in .env files so the best remedy would be to prevent them appearing in KV pairs at all.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535489668000300) today, we're keeping this in the `1.0.0` release as `nice to have` and at the very least we add some docs.

**Comment by jeffpaul** [comment]
Note that this issue was [referenced in Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1543354233123100).

**Comment by valendesigns** [comment]
Since the key and secret for local development have been updated and do not contain any hash symbols all we need to do here is ensure that the key and secret in the `wp-tide-api` plugin don't add a hash. The auto generated key already doesn't add a hash because special_chars are set to false in the call to `wp_generate_password`. I've updated the plugin to make sure the secret has the `#` replaced with `$`.
