### ISSUE TITLE
Test new AS output

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#19]
- [ ] grab 3 plugins and 3 themes output from currently active API
- [ ] grab the same plugins and themes output from the rewritten GCP-version of the AS
- [ ] compare output and log Issues where there are differences

**Comment by danlouw** [comment]
With the latest changes I am able to build and run both the Lighthouse and PHPCS servers, but then I get:

```
lighthouse-server_1  | 2018/02/26 14:41:25 Polling...
lighthouse-server_1  | 2018/02/26 14:41:27 Polling...
phpcs-server_1       | 2018/02/26 14:41:27 send request failed
phpcs-server_1       | 2018/02/26 14:41:27 Polling...
```

And messages in the queue are not being picked up.

This would seem to indicate that the PHPCS server is unable to connect to SQS, even though my `.env` file is configured as before.

I will connect with @rheinardkorf  tomorrow to see if he has any insights on the issue

**Comment by danlouw** [comment]
By debugging with Rheinard we were able to confirm that the issue is not in the Go code, since we are able to access the SQS queue when running `main.go` stand-alone.

This means that the issue is with the Docker container.

Continuing debugging to determine what's going wrong.

**Comment by rheinardkorf** [comment]
Not sure if this is a potential issue or not, @valendesigns , do we need ssl root certs installed in the image or do they already exist?

**Comment by valendesigns** [comment]
@rheinardkorf We're not running `ssh`, so why would we need the certs for it?

**Comment by rheinardkorf** [comment]
@valendesigns I meant ssl.... wondering if accessing any of the aws sdks requires it. Stab in the dark :)

**Comment by valendesigns** [comment]
Maybe, I'll add them and then we can test. Give me a couple minutes.

**Comment by valendesigns** [comment]
@danlouw & @rheinardkorf please pull the changes in https://github.com/xwp/go-tide/pull/21 and rebuild the image to test

**Comment by rheinardkorf** [comment]
@valendesigns bingo! that did the trick... merging the PR.

**Comment by rheinardkorf** [comment]
@valendesigns now I'm curious what my comment was :D

**Comment by danlouw** [comment]
Thanks @valendesigns and @rheinardkorf ! My PHPCS server now has access to SQS and can initiate audits based on messages in the queue.

I am seeing some issues with auditing and sending results back to Tide API though. Investigating now and will report back with details.

**Comment by danlouw** [comment]
@rheinardkorf  , sorry about this essay, but maybe it can help to resolve some of the issues I’m seeing async.

Here’s an example of what’s happening with the PHPCS Server in my local:

I’ve placed a message for the Twenty Seventeen theme in the SQS queue.

When I start the PHPCS Server it starts polling the queue and picks up the message, but then gives the following output:

```
phpcs-server_1       | 2018/02/27 09:56:03 Polling...
phpcs-server_1       | 2018/02/27 09:56:03 twentyseventeen theme (results pending): Processing...
phpcs-server_1       | 2018/02/27 09:56:03 twentyseventeen theme (results pending): Ingesting...
phpcs-server_1       | 2018/02/27 09:56:05 Polling...
phpcs-server_1       | 2018/02/27 09:56:06 twentyseventeen theme (results pending): Project checksum: `ab38727534cbeeef043faf1e54a786e22e4e7c6a172a5ccccf23fe6b2f3d28bd`
phpcs-server_1       | 2018/02/27 09:56:06 twentyseventeen theme (results pending): Processing CodeInfo
phpcs-server_1       | 2018/02/27 09:56:06 twentyseventeen theme (results pending): Project is `theme`
phpcs-server_1       | 2018/02/27 09:56:06 twentyseventeen theme (results pending): Running PHPCS Audit...
phpcs-server_1       | 2018/02/27 09:56:07 twentyseventeen theme (results pending): phpcs output:
phpcs-server_1       |  Time: 945ms; Memory: 14Mb
phpcs-server_1       | 2018/02/27 09:56:07 twentyseventeen theme (results pending): Uploading phpcs_wordpress results to remote storage.
phpcs-server_1       | 2018/02/27 09:56:08 Polling...
phpcs-server_1       | 2018/02/27 09:56:09 twentyseventeen theme (results pending): Post-Processing: phpcs_summary
phpcs-server_1       | 2018/02/27 09:56:09 twentyseventeen theme (results pending): phpcs (wordpress) process completed with exit code: 2
phpcs-server_1       | 2018/02/27 09:56:09 twentyseventeen theme (results pending): Running PHPCS Audit...
phpcs-server_1       | 2018/02/27 09:56:09 twentyseventeen theme (results pending): phpcs output:
phpcs-server_1       |  Time: 181ms; Memory: 10Mb
phpcs-server_1       | 2018/02/27 09:56:09 twentyseventeen theme (results pending): Uploading phpcs_phpcompatibility results to remote storage.
phpcs-server_1       | 2018/02/27 09:56:09 twentyseventeen theme (results pending): Post-Processing: phpcs_phpcompat
phpcs-server_1       | 2018/02/27 09:56:10 twentyseventeen theme (results pending): phpcs (phpcompatibility) process completed with exit code: 0
phpcs-server_1       | 2018/02/27 09:56:10 twentyseventeen theme (results pending): Preparing Tide API payload...
phpcs-server_1       | 2018/02/27 09:56:10 twentyseventeen theme (results pending): Using existing audit for payload.
phpcs-server_1       | 2018/02/27 09:56:10 twentyseventeen theme (results pending): Sending payload to Tide API...
phpcs-server_1       | 2018/02/27 09:56:10 Polling...
phpcs-server_1       | 2018/02/27 09:56:10 twentyseventeen theme (results pending): Unexpected status code.
phpcs-server_1       | 2018/02/27 09:56:10 twentyseventeen theme (results pending): Completed with some errors.
phpcs-server_1       | 2018/02/27 09:56:12 Polling...
```

Note specifically: `phpcs (wordpress) process completed with exit code: 2`, `Unexpected status code.` and `Completed with some errors.`

I’m not sure if the `Unexpected status code.` is caused by the `phpcs` non-zero exit code (API rejecting the request maybe?), whatever the cause, the PHPCS Server is unable to send any results back to the Tide API (audit in the API remains unchanged and message remains in queue)

I’ve tried to debug what’s happening with `phpcs (wordpress)` but when GoLand’s `Go Build` builds and runs `phpcs-server` I can’t get past this part in the code: 

https://github.com/wptide/pkg/blob/master/audit/phpcs/phpcs.go#L126

Since `err` has the following value there: `executable file not found in $PATH`

I take that to mean that GoLand does not recognised the `phpcs` command (although it is in the PATH of my host machine). Do you agree with that assessment? Whatever it is, its unique to running in GoLand. The actual `phpcs-server` is at least able to run `phpcs` (even though it gets a non-zero exit code).

I’ve tried a few approaches to get around this, but no success. Any ideas?

As an alternative to debugging code compiled by GoLand’s `Go Build` debugging functionality, I’ve tried to directly debug the compiled code running on the container.

I first tried GoLand’s `Go Remote`, but as we’ve found this morning, I need to setup Delve and Go on the container for this to work and I’m having issues with that.

I’ve gotten as far as installing Go on the running `phpcs-server` container, but can’t seem to call the Go command (not even from directly within the container’s `/usr/local/go/bin` directory). I keep getting `sh: ./go: not found`. Not sure if it’s weird shell behaviour specific to the container or if I didn’t install Go correctly.

Have you been able to make any progress with `Go Remote` debugging?

As a last resort I've tried to get `phpcs.go` to log some additional debugging info by using `log.Log()` in a few places, but I'm having limited success getting my changes into the compiled code. Whenever I build `phpcs-server`, the version of `phpcs.go` in `go-tide`’s `vendor` folder reverts back to the original (without my changes). So I’m not sure how to get the temporary changes into `pkg` code without actually committing it to GitHub (which we obviously don’t want).

Anyway, that’s how far I got. I’m interested to hear if you also get the `phpcs (wordpress) process completed with exit code: 2` issue and your thoughts on a better approach for Go debugging.

**Comment by danlouw** [comment]
@rheinardkorf @valendesigns , I’ve now been able to sort out issues with `phpcs` in GoLand debugging, which enabled me to find the source of the `Unexpected status code.` from Tide API.

The short version is:  The Go PHPCS Server does not support a specific audit post (post ID) route as `response_api_endpoint`.

I’ve been using the “Audit Request via API” use case for testing, where I send a request to the Tide API, which then creates an audit post and SQS message.

The crucial difference between the Sync Server use case and the “Audit Request via API” use case is the `response_api_endpoint`.

An SQS message created by the Sync Server has the `audit` collection endpoint as `response_api_endpoint`, e.g. http://tide.local/api/tide/v1/audit, while an SQS message created by the Tide API has a specific audit post (post ID) route as `response_api_endpoint`, e.g. http://tide.local/api/tide/v1/audit/151.

The Go PHPCS Server does not expect the latter.

I can confirm that when I follow the Sync Server use case, e.g. manually create an SQS message with the `audit` collection endpoint as `response_api_endpoint`, I am able to get `Completed without errors.` - the Tide API accepts the results sent to the checksum route and creates a new audit post.

The relevant piece of code is in `getValidItem()` in `pkg/audit/tide/tide.go` (https://github.com/wptide/pkg/blob/master/audit/tide/tide.go#L197):

```
// Some values should only be set if it was a collection endpoint.
if isCollection || msg.Force {
```

When `response_api_endpoint` is a post ID route, all of these values in `getValidItem()` (Title, Description, ProjectType, Version, etc.) are left empty in the payload, which causes the Tide API to respond with a `500` response of `Unexpected '<'`, which is a bit confusing, but the message refers to the empty Content field (providing a value for Content makes the Tide API accept the request, even with the other fields still empty).

I’m not sure if we were planning to support the “Audit Request via API” use case, but the current implementation is a definite deviation from the old PHP Audit Server.

**Comment by rheinardkorf** [comment]
@danlouw thanks! That is very useful feedback. 

There is logic in `ingest.go` to attempt to get existing results from the Tide API (https://github.com/wptide/pkg/blob/master/audit/ingest/ingest.go#L58) which then adds this to r["tideItem"].  Then in `tide.go` we attempt to use an existing result (from the post endpoint) as the payload.  

If this was not a collection endpoint (e.g. a post endpoint) then the audit should be send back to that endpoint. If its a collection endpoint then it will send to a checksum endpoint (https://github.com/wptide/pkg/blob/master/audit/tide/tide.go#L72-L78).

There is obviously a flaw in some logic here.  The phpcs server should honour the provided endpoint.  

The intend is for it to work like the Symfony app still. Thanks for debugging, this is helpful for me when I am back at my desk tomorrow.

**Comment by rheinardkorf** [comment]
@danlouw @valendesigns I have discovered the cause of this issue.  It is located in https://github.com/wptide/pkg/blob/master/audit/tide/tide.go#L198-L214

I check here for validation if it is a collection endpoint because if you send a payload to an existing WP post you do not need to provide all fields.  The problem, however, is that the payload doesn't omit the fields, it sends empty fields. That is not ideal.

The code is turned into JSON here: https://github.com/wptide/pkg/blob/master/audit/tide/tide.go#L146
Unfortunately when you marshal an object it will add empty values for missing fields, unless we add `omitempty` to the fields in https://github.com/wptide/pkg/blob/master/tide/item.go#L9-L20

All that said, with the Symfony server we correctly updated post details based on the information from CodeInfo.  So to stay true to the Symfony app I can remove the condition in `getValidItem` and apply it to all payloads. Which means I don't have to use the `omitempty` solution above.  Where if we are going like-for-like, this seems the better solution.

**Comment by jeffpaul** [comment]
Closing per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1534882016000100) as work was done and validated elsewhere.
