### ISSUE TITLE
GitHub webhook/HTTP Listener

### ISSUE THREAD

**Issue by valendesigns** [wptide/wptide#44]

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1534882210000100) today, we're tagging this to `Future Release`

**Comment by jeffpaul** [comment]
Notes from @rheinardkorf via Slack:
For Git integration:

- Create a new plugin
- Plugin creates endpoint for GitHub webhook PR event
-- When a PR gets created or updated we can get the ZIP source from `http://github.com/<user>/<project>/archive/<sha>.zip`
-- Add GH status for each audit type as pending
-- Use `add_task` to create a new audit task which will fire off to the audit servers
-- Endpoint will be the new one below.
- Plugin creates endpoint for processed GitHub audit (to send back results to GH)
-- When audit is done then it sends back to this endpoint, not the normal audit endpoint
-- This endpoint will create a new audit, but tag it for GH, because we want to be able to see it when clicking on the link from the PR
-- After post is created/updated set the GH status for the PR with relevant status message.

**Comment by valendesigns** [comment]
Closing, this is out of scope for this project.
